services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: tienda_isela
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/posgresql/data
    ports:
      - 5432:5432

volumes:
  pgdata:
